### ISSUE TITLE
Release a new version maybe?

### ISSUE THREAD

**Issue by miccheng** [sourcelevel/faraday-http-cache#117]
Looks like master is 28 commits ahead of `2.0.0`. Any thoughts about releasing a new version soon? Or perhaps back patching fixes to `1.x.x`? 

Eg: https://github.com/plataformatec/faraday-http-cache/commit/5567e12b08920e6b4e57dddd9295e898f725bae8 <-- would be nice to have in `1.2.3` and `1.3.2`.

**Comment by georgeguimaraes** [comment]
I've just released `2.1.0` with what we had in master. I'd appreciate it if you could test the new version. :)
