### ISSUE TITLE
Support Faraday 1.0

### ISSUE THREAD

**Issue by ybiquitous** [sourcelevel/faraday-http-cache#118]
Hi,

Do you have a plan to support Faraday 1.0, which will be released soon?

The latest version 0.17.3 of Faraday is the last version of the 0.x series.

https://github.com/lostisland/faraday/releases/tag/v0.17.3

**Comment by ybiquitous** [comment]
FYI. https://github.com/lostisland/faraday/blob/master/UPGRADING.md

**Comment by johnlcox** [comment]
Is there any ETA on when 1.0 support might be available and released?

**Comment by ybiquitous** [comment]
The 1.0 due date seems May 3, 2020:
https://github.com/lostisland/faraday/milestone/1

**Comment by marnen** [comment]
1.0 was already released in December. It's a pity that the released version of this gem doesn't support it.

**Comment by georgeguimaraes** [comment]
Hi, have you tried updating the dependency to Faraday 1.0? I'll take a look into that.

**Comment by ybiquitous** [comment]
Thank you! It seems that the dependency has been updated via the commit 88772d9349645f873f5db6b787ddf810a860486f!

Looks like this issue can be closed if nobody has an opinion. 😃

**Comment by marnen** [comment]
@ybiquitous Except that commit hasn’t made it into a release yet, right?

**Comment by ybiquitous** [comment]
Yes. I hope it will be released soon. 😃

**Comment by ioquatix** [comment]
Can you please release it?

**Comment by ioquatix** [comment]
@georgeguimaraes friendly ping :)

**Comment by georgeguimaraes** [comment]
Released! https://rubygems.org/gems/faraday-http-cache/versions/2.2.0 
I haven't tried it with the newer Faraday versions. Please let me know if things break. :)

**Comment by ybiquitous** [comment]
@georgeguimaraes Thank you!
