### ISSUE TITLE
When checking headers specified in Vary, the header names should be checked with a fallback to downcasing

### ISSUE THREAD

**Issue by evman182** [sourcelevel/faraday-http-cache#136]
For the following line:
https://github.com/sourcelevel/faraday-http-cache/blob/d05c59063bbdcc621a9320035872a5fb0822973b/lib/faraday/http_cache/strategies/by_url.rb#L102

my suggestion is it be changed to 
```ruby
 request.headers[header] == (cached_request[:headers][header] || cached_request[:headers][header.downcase])
```

This is based on the fact that rack and Faraday Header classes both seem to downcase the keys
https://github.com/rack/rack/blob/3897649e8740e560a5fa142f972121a119b26b5c/lib/rack/headers.rb#L110-L116

https://github.com/lostisland/faraday/blob/cc5d60776645d3d341ff0f425c45b3b3d48d98e0/lib/faraday/utils/headers.rb#L52-L63

**Comment by georgeguimaraes** [comment]
Hi @evman182! Tks for the suggestion, it makes a lot of sense.
Would you mind sending a PR? Not sure if we have tests covering this part, but a test on this logic would be awesome too.

**Comment by georgeguimaraes** [comment]
https://github.com/sourcelevel/faraday-http-cache/pull/137
