### ISSUE TITLE
POSTs don't always trigger invalidation for the appropriate cache entries

### ISSUE THREAD

**Issue by dobbymoodge** [sourcelevel/faraday-http-cache#95]
My situation involves the GitHub API (using Octokit) but I'd be surprised if this didn't affect other services.

I get the list of comments for an issue, and the request is something like:
`GET https://api.github.com/repos/{:user}/{:repo}/issues/{:issue_id}/comments?per_page=100`
I add a new comment and the request looks like:
`POST https://api.github.com/repos/{:user}/{:repo}/issues/{:issue_id}/comments {:body => "comment"}`
If I GET the issue comments immediately after I POST, I don't get the updated comments list when caching is enabled. My understanding is that the POST should have triggered deletion of the cached response from earlier since #57 went in.

From what I can tell, I think the GET requests are keyed in the cache by their URL including the params (`?per_page=100` in my example). The POST request isn't paginated, so the URL doesn't exactly match the GET URL, and thus doesn't trigger the appropriate cache entry deletion. (I think)

I imagine there are plenty of cases where this behavior is in fact correct, but in this particular case I would like any cache entries like `.start_with?(<POST url>)` to be deleted. Some possible approaches would be:

- Allow specifying a set of patterns that identify a class of URLs which should be invalidated together when a matching POST request is made. This would probably need to be tracked in its own object, e.g. a `Hash` like `{<pattern> => [<list of cache keys for matching entries>]}`

- Allow passing a parameter for GET requests like `:bypass_cache => true` in the `options` field that triggers the matching request to be deleted from the cache

This is a pretty frustrating wrinkle for me right now :(

**Comment by ryuichi7** [comment]
Hi @dobbymoodge, I just opened a PR that might help with this issue https://github.com/plataformatec/faraday-http-cache/pull/97. It would allow you to customize the cache_key (essentially you could strip the pagination query param when storing the key)
